### ISSUE TITLE
json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by tbanov** [esign/laravel-conversions-api#15]
I am getting e 500 error from time to time, from bots which are scanning my application, here is the log:

![image](https://github.com/user-attachments/assets/e195f773-fce1-4dc1-9b0f-a5ff783de476)

Here is the content of the file facebook-pixel.blade.php

![image](https://github.com/user-attachments/assets/40e0a894-da58-4f14-bcb8-ad4867936e57)

Please advise?

**Comment by jordyvanderhaegen** [comment]
Hi @tbanov, can you please provide a stack trace including the data being passed to the `json_encode` method?

**Comment by tbanov** [comment]
Hi @jordyvanderhaegen and thank you for your work

Unfortunately I can't find the passed data in my logs, I have tried to reproduce the issue but with no success for now.

In the man time here is the stack trace:

`"#0 /app/vendor/guzzlehttp/guzzle/src/functions.php(166): GuzzleHttp\Utils::jsonEncode(Array, 0, 512)
#1 /app/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/EventRequestAsync.php(82): GuzzleHttp\json_encode(Array)
#2 /app/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/EventRequestAsync.php(51): FacebookAds\Object\ServerSide\EventRequestAsync->eventPromise('706800900325278...', Array)
#3 /app/vendor/esign/laravel-conversions-api/src/ConversionsApi.php(77): FacebookAds\Object\ServerSide\EventRequestAsync->execute()
#4 /app/vendor/esign/laravel-conversions-api/src/View/Components/FacebookPixelPageView.php(13): Esign\ConversionsApi\ConversionsApi->sendEvents()
#5 /app/vendor/laravel/framework/src/Illuminate/View/Component.php(102): Esign\ConversionsApi\View\Components\FacebookPixelPageView->__construct()
#6 /app/resources/views/layouts/facebook-pixel.blade.php(3): Illuminate\View\Component::resolve(Array)
#7 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(123): require('/app/storage/fr...')
#8 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#9 /app/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/app/storage/fr...', Array)
#10 /app/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/storage/fr...', Array)
#11 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->evaluatePath('/app/storage/fr...', Array)
#12 /app/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\View\Engines\CompilerEngine->get('/app/resources/...', Array)
#13 /app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(35): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->get('/app/resources/...', Array)
#14 /app/vendor/laravel/framework/src/Illuminate/View/View.php(207): Sentry\Laravel\Tracing\ViewEngineDecorator->get('/app/resources/...', Array)
#15 /app/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#16 /app/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#17 /app/resources/views/layouts/public/partials/head.blade.php(31): Illuminate\View\View->render()`
```




"#0 /app/vendor/guzzlehttp/guzzle/src/functions.php(166): GuzzleHttp\Utils::jsonEncode(Array, 0, 512)
#1 /app/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/EventRequestAsync.php(82): GuzzleHttp\json_encode(Array)
#2 /app/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/EventRequestAsync.php(51): FacebookAds\Object\ServerSide\EventRequestAsync->eventPromise('706800900325278...', Array)
#3 /app/vendor/esign/laravel-conversions-api/src/ConversionsApi.php(77): FacebookAds\Object\ServerSide\EventRequestAsync->execute()
#4 /app/vendor/esign/laravel-conversions-api/src/View/Components/FacebookPixelPageView.php(13): Esign\ConversionsApi\ConversionsApi->sendEvents()
#5 /app/vendor/laravel/framework/src/Illuminate/View/Component.php(102): Esign\ConversionsApi\View\Components\FacebookPixelPageView->__construct()
#6 /app/resources/views/layouts/facebook-pixel.blade.php(3): Illuminate\View\Component::resolve(Array)
#7 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(123): require('/app/storage/fr...')
#8 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#9 /app/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/app/storage/fr...', Array)
#10 /app/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/storage/fr...', Array)
#11 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->evaluatePath('/app/storage/fr...', Array)
#12 /app/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\View\Engines\CompilerEngine->get('/app/resources/...', Array)
#13 /app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(35): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->get('/app/resources/...', Array)
#14 /app/vendor/laravel/framework/src/Illuminate/View/View.php(207): Sentry\Laravel\Tracing\ViewEngineDecorator->get('/app/resources/...', Array)
#15 /app/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#16 /app/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#17 /app/resources/views/layouts/public/partials/head.blade.php(31): Illuminate\View\View->render()

**Comment by jordyvanderhaegen** [comment]
@tbanov thank you for providing the stacktrace, I gave this a look but couldn't figure out what's causing this issue. In case you can provide a reproducible example, that would be great. In the meantime, see if adding the `JSON_INVALID_UTF8_IGNORE` or `JSON_INVALID_UTF8_SUBSTITUTE` flags to the `@json` helper resolves the issue. You may pass these by publishing the views of this package, see [Installation](https://github.com/esign/laravel-conversions-api/tree/master?tab=readme-ov-file#installation) instructions for more details.

**Comment by jordyvanderhaegen** [comment]
Closing this due to lack of details on how to reproduce this. If the problem persists, please feel free to open a new issue with more detailed information.

**Comment by neamtua** [comment]
I also have this error and I've asked the jetbrains AI to analyze. It suggested that in the middleware to extend the DefaultUserData class and do "$userAgent = mb_convert_encoding($userAgent, 'UTF-8', 'UTF-8');" on the user agent. Going to try this solution and tell you if I get this error again or not.

Looking at my errors i can see the offending user agents look like "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html��"
